### ISSUE TITLE
 SystemError: Running HomeAssistant 2024.1.2, Minimum required version >=2023.6.0

### ISSUE THREAD

**Issue by shtrom** [ldotlopez/ha-historical-sensor#12]
Hey there,

It looks like there is a compat bug with HA 2024.

The following was reported against https://github.com/LeighCurran/AuroraPlusHA/pull/9 (in https://github.com/LeighCurran/AuroraPlus/pull/3#issuecomment-1884213483), but the error seems to be coming from the historical sensor integration:

```
Traceback (most recent call last):
File "/usr/src/homeassistant/homeassistant/loader.py", line 842, in get_platform
cache[full_name] = self._import_platform(platform_name)
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "/usr/src/homeassistant/homeassistant/loader.py", line 859, in _import_platform
return importlib.import_module(f"{self.pkg_path}.{platform_name}")
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "/usr/local/lib/python3.11/importlib/init.py", line 126, in import_module
return _bootstrap._gcd_import(name[level:], package, level)
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "", line 1204, in _gcd_import
File "", line 1176, in _find_and_load
File "", line 1147, in _find_and_load_unlocked
File "", line 690, in _load_unlocked
File "", line 940, in exec_module
File "", line 241, in _call_with_frames_removed
File "/config/custom_components/auroraplus/sensor.py", line 39, in
from homeassistant_historical_sensor import (
File "/usr/local/lib/python3.11/site-packages/homeassistant_historical_sensor/init.py", line 39, in
raise SystemError(msg)
SystemError: Running HomeAssistant 2024.1.2, Minimum required version >=2023.6.0
```

The version comparison looks good to me, so I guess something else's at play.

**Comment by ldotlopez** [comment]
Hi @shtrom

It was fixed in https://github.com/ldotlopez/ha-historical-sensor/commit/69c05a58b6784a6bfee9bd6dba2d395120ab976f

Update your manifest.json to require a more recent version, like '2.0.0rc5' 

Please, ping me with any update.
